"""initial schema: all 6 core tables

Hand-written (not autogenerated) so the Postgres-specific bits — UUID PKs
with gen_random_uuid(), JSONB, ARRAY, CHECK constraints, composite PK —
are explicit and reviewed. Tables are created in FK-dependency order and
dropped in reverse.

Revision ID: 0001_initial_schema
Revises:
Create Date: stage 1
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _uuid_pk_col() -> sa.Column:
    return sa.Column(
        "id",
        postgresql.UUID(as_uuid=True),
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    )


def _ts(name: str, *, nullable: bool = False) -> sa.Column:
    return sa.Column(
        name,
        sa.DateTime(timezone=True),
        server_default=None if nullable else sa.text("now()"),
        nullable=nullable,
    )


def upgrade() -> None:
    op.create_table(
        "users",
        _uuid_pk_col(),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        _ts("created_at"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )

    op.create_table(
        "tags",
        _uuid_pk_col(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        _ts("created_at"),
        _ts("updated_at"),
        _ts("deleted_at", nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_tags_user_id"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["tags.id"], name="fk_tags_parent_id"
        ),
    )
    op.create_index("ix_tags_user_id", "tags", ["user_id"])
    op.create_index("ix_tags_parent_id", "tags", ["parent_id"])
    op.create_index("ix_tags_path", "tags", ["path"])

    op.create_table(
        "questions",
        _uuid_pk_col(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("stem", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("options", postgresql.JSONB(), nullable=False),
        sa.Column("correct", postgresql.JSONB(), nullable=False),
        sa.Column("knowledge_summary", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        _ts("created_at"),
        _ts("updated_at"),
        _ts("deleted_at", nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_questions_user_id"
        ),
        sa.CheckConstraint(
            "type IN ('single', 'multi', 'judge')", name="ck_questions_type"
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'ocr', 'ai')", name="ck_questions_source"
        ),
    )
    op.create_index("ix_questions_user_id", "questions", ["user_id"])

    op.create_table(
        "question_tags",
        sa.Column(
            "question_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("tag_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("question_id", "tag_id"),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            ondelete="CASCADE",
            name="fk_question_tags_question_id",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            ondelete="CASCADE",
            name="fk_question_tags_tag_id",
        ),
    )
    op.create_index("ix_question_tags_tag_id", "question_tags", ["tag_id"])

    op.create_table(
        "review_logs",
        _uuid_pk_col(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "question_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("correct", sa.Boolean(), nullable=False),
        _ts("answered_at"),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_review_logs_user_id"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name="fk_review_logs_question_id",
        ),
    )
    op.create_index(
        "ix_review_logs_user_answered",
        "review_logs",
        ["user_id", "answered_at"],
    )

    op.create_table(
        "gen_sessions",
        _uuid_pk_col(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "seed_question_ids",
            postgresql.ARRAY(postgresql.UUID(as_uuid=True)),
            nullable=False,
        ),
        _ts("created_at"),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_gen_sessions_user_id"
        ),
    )
    op.create_index("ix_gen_sessions_user_id", "gen_sessions", ["user_id"])


def downgrade() -> None:
    # Reverse FK-dependency order. Dropping a table also drops its indexes.
    op.drop_table("gen_sessions")
    op.drop_table("review_logs")
    op.drop_table("question_tags")
    op.drop_table("questions")
    op.drop_table("tags")
    op.drop_table("users")
